steps:
- id: 'branch start'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "Starting Terraform Job"
      echo "***********************"
# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "Terraform init"
      terraform init
# [END tf-init]
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "Terraform plan"
      terraform plan
# [END tf-plan]
# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
   - '-c'
   - |
       echo "Terraform apply"
       terraform apply --auto-approve
#[END tf-apply]

options:
  logging: CLOUD_LOGGING_ONLY
